services:
  - type: web
    name: evolution-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: SERVER_PORT
        value: 3000
